### ISSUE TITLE
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

### ISSUE THREAD

**Issue by Weekcat** [KuangDD/aukit#4]
在conda环境下pip安装失败

> Using cached aukit-1.4.0.tar.gz (20 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/weekmon/anaconda3/envs/speech/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-c3qragc5/aukit/setup.py'"'"'; __file__='"'"'/tmp/pip-install-c3qragc5/aukit/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-gyfh753c
         cwd: /tmp/pip-install-c3qragc5/aukit/
    Complete output (49 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-c3qragc5/aukit/setup.py", line 26, in <module>
        from aukit import __version__ as aukit_version
      File "/tmp/pip-install-c3qragc5/aukit/aukit/__init__.py", line 34, in <module>
        from .audio_io import load_wav, save_wav, anything2bytesio, anything2wav, anything2bytes, Dict2Obj, _sr
      File "/tmp/pip-install-c3qragc5/aukit/aukit/audio_io.py", line 18, in <module>
        import librosa
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/librosa/__init__.py", line 12, in <module>
        from . import core
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/librosa/core/__init__.py", line 125, in <module>
        from .time_frequency import *  # pylint: disable=wildcard-import
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/librosa/core/time_frequency.py", line 11, in <module>
        from ..util.exceptions import ParameterError
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/librosa/util/__init__.py", line 77, in <module>
        from .utils import *  # pylint: disable=wildcard-import
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/librosa/util/utils.py", line 10, in <module>
        import numba
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/__init__.py", line 47, in <module>
        import numba.typed
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/typed/__init__.py", line 3, in <module>
        from .typeddict import Dict
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/typed/typeddict.py", line 18, in <module>
        @njit
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/decorators.py", line 239, in njit
        return jit(*args, **kws)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/decorators.py", line 176, in jit
        return wrapper(pyfunc)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/decorators.py", line 192, in wrapper
        **dispatcher_args)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/dispatcher.py", line 650, in __init__
        self.targetctx = self.targetdescr.target_context
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/registry.py", line 50, in target_context
        return self._toplevel_target_context
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/utils.py", line 390, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
        return cpu.CPUContext(self.typing_context)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/base.py", line 250, in __init__
        self.init()
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
        return func(*args, **kwargs)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/cpu.py", line 51, in init
        self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/codegen.py", line 612, in __init__
        self._init(self._llvm_module)
      File "/home/weekmon/anaconda3/envs/speech/lib/python3.6/site-packages/numba/targets/codegen.py", line 621, in _init
        tm = target.create_target_machine(**tm_options)
    TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

尝试过重装numba得到一样结果

**create_target_machine()**

>     
        def create_target_machine(self, cpu='', features='',
                              opt=2, reloc='default', codemodel='jitdefault',
                              printmc=False, jit=False):
        """
        Create a new TargetMachine for this target and the given options.

        Specifying codemodel='default' will result in the use of the "small"
        code model. Specifying codemodel='jitdefault' will result in the code
        model being picked based on platform bitness (32="small", 64="large").

        The `printmc` option corresponds to llvm's `-print-machineinstrs`.

        The `jit` option should be set when the target-machine is to be used
        in a JIT engine.
        """
        assert 0 <= opt <= 3
        assert reloc in RELOC
        assert codemodel in CODEMODEL
        triple = self._triple
        # MCJIT under Windows only supports ELF objects, see
        # http://lists.llvm.org/pipermail/llvm-dev/2013-December/068341.html
        # Note we still want to produce regular COFF files in AOT mode.
        if os.name == 'nt' and codemodel == 'jitdefault':
            triple += '-elf'
        tm = ffi.lib.LLVMPY_CreateTargetMachine(self,
                                                _encode_string(triple),
                                                _encode_string(cpu),
                                                _encode_string(features),
                                                opt,
                                                _encode_string(reloc),
                                                _encode_string(codemodel),
                                                int(printmc),
                                                int(jit),
                                                )
        if tm:
            return TargetMachine(tm)
        else:
            raise RuntimeError("Cannot create target machine")

尝试过想更改create_target_machine()，但因为水平有限未能解决

包的安装应该都是按照[KuangDD/zhrtvc/requirements_with_version.txt](https://github.com/KuangDD/zhrtvc/blob/master/zhrtvc/requirements_with_version.txt)安装的，不确定使用虚拟环境会不会有影响

**conda list**

> Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_tflow_select             2.1.0                       gpu  
absl-py                   0.9.0                    py36_0  
astor                     0.8.0                    py36_0  
audioread                 2.1.8                    pypi_0    pypi
blas                      1.0                         mkl  
c-ares                    1.15.0            h7b6447c_1001  
ca-certificates           2020.1.1                      0  
certifi                   2020.4.5.2               py36_0  
cffi                      1.14.0                   pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
cudatoolkit               10.0.130                      0  
cudnn                     7.6.5                cuda10.0_0  
cupti                     10.0.130                      0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
dill                      0.3.2                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                      py_0  
get                       2019.4.13                pypi_0    pypi
grpcio                    1.27.2           py36hf8bcb03_0  
h5py                      2.10.0           py36h7918eee_0  
hanziconv                 0.3.2                    pypi_0    pypi
hdf5                      1.10.4               hb1b8bf9_0  
idna                      2.9                      pypi_0    pypi
importlib-metadata        1.6.1                    pypi_0    pypi
inflect                   4.1.0                    pypi_0    pypi
intel-openmp              2020.1                      217  
jieba                     0.42.1                   pypi_0    pypi
joblib                    0.15.1                   pypi_0    pypi
jsonpatch                 1.25                     pypi_0    pypi
jsonpointer               2.0                      pypi_0    pypi
keras                     2.3.0                    pypi_0    pypi
keras-applications        1.0.8                      py_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h7b6447c_0  
libffi                    3.3                  he6710b0_1  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libprotobuf               3.12.3               hd408876_0  
librosa                   0.7.2                    pypi_0    pypi
libstdcxx-ng              9.1.0                hdf63c60_0  
llvmlite                  0.33.0                   pypi_0    pypi
markdown                  3.1.1                    py36_0  
matplotlib                2.2.3                    pypi_0    pypi
mkl                       2020.1                      217  
mkl-service               2.3.0            py36he904b0f_0  
mkl_fft                   1.1.0            py36h23d657b_0  
mkl_random                1.1.1            py36h0573a6f_0  
mock                      4.0.2                      py_0  
multiprocess              0.70.9                   pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
numba                     0.46.0                   pypi_0    pypi
numpy                     1.18.4                   pypi_0    pypi
openssl                   1.1.1g               h7b6447c_0  
phkit                     0.2.1                    pypi_0    pypi
pillow                    7.1.2                    pypi_0    pypi
pip                       20.1.1                   py36_1  
post                      2019.4.13                pypi_0    pypi
protobuf                  3.12.3           py36he6710b0_0  
public                    2019.4.13                pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pydub                     0.23.1                   pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pypinyin                  0.38.0                   pypi_0    pypi
pyqt5                     5.15.0                   pypi_0    pypi
pyqt5-sip                 12.8.0                   pypi_0    pypi
python                    3.6.10               h7579374_2  
python-dateutil           2.8.1                    pypi_0    pypi
python-speech-features    0.6                      pypi_0    pypi
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.1                   pypi_0    pypi
query-string              2019.4.13                pypi_0    pypi
readline                  8.0                  h7b6447c_0  
request                   2019.4.13                pypi_0    pypi
requests                  2.24.0                   pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
scikit-learn              0.23.1                   pypi_0    pypi
scipy                     1.4.1            py36h0b6359f_0  
setuptools                47.3.1                   pypi_0    pypi
six                       1.15.0                     py_0  
sounddevice               0.3.14                   pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.32.2               h62c20be_0  
tbb                       2020.0.133               pypi_0    pypi
tensorboard               1.13.1           py36hf484d3e_0  
tensorflow-estimator      1.13.0                     py_0  
tensorflow-gpu            1.13.1               h0d30ee6_0  
termcolor                 1.1.0                    py36_1  
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch                     1.5.0                    pypi_0    pypi
torchfile                 0.1.0                    pypi_0    pypi
tornado                   6.0.4                    pypi_0    pypi
tqdm                      4.26.0                   pypi_0    pypi
umap                      0.1.1                    pypi_0    pypi
umap-learn                0.4.4                    pypi_0    pypi
unidecode                 1.1.1                    pypi_0    pypi
urllib3                   1.25.9                   pypi_0    pypi
visdom                    0.1.8.9                  pypi_0    pypi
wave                      0.0.2                    pypi_0    pypi
webrtcvad                 2.0.10                   pypi_0    pypi
websocket-client          0.57.0                   pypi_0    pypi
werkzeug                  1.0.1                      py_0  
wheel                     0.34.2                   py36_0  
xz                        5.2.5                h7b6447c_0  
zipp                      3.1.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  

OS：Ubuntu 20.04
很抱歉我无法在非虚拟环境下测试，请问有解决办法吗？谢谢！

**Comment by naah69** [comment]
+1

**Comment by KuangDD** [comment]
试试先安装numba==0.48，再安装librosa，最后安装aukit。
安装完librosa，测试一下librosa是否安装成功。

pip install numba==0.48
pip install -U librosa
pip install -U aukit

**Comment by Weekcat** [comment]
安装成功了，非常感谢！
