### ISSUE TITLE
maybe bug when use DotMap

### ISSUE THREAD

**Issue by JohnHerry** [KuangDD/aukit#5]
用DotMap做属性管理的时候，如果这个属性之前在你的hparams字典里没定义过，那么后边访问时：
dotmap_obj.abc
它就会给你生成这样一个属性，且值为一个空的DotMap：  DotMap()

所以比如这段逻辑：
audio_griffinlim.py:352

'''
    if hparams.inv_mel_basis is None:
        _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
    else:
        _inv_mel_basis = hparams.inv_mel_basis
    return np.maximum(1e-10, np.dot(_inv_mel_basis, mel_spectrogram))
'''

我没定义过inv_mel_basis这个属性，这个函数会抛出异常： mp.dot 不支持一个DotMap对象，跟一个浮点数相乘。
如果必须要用DotMap，预计逻辑是不是应该这样的？

'''
    if “inv_mel_basis” not in hparams or hparams.inv_mel_basis is None:
         _inv_mel_basis = np.linalg.pinv(_build_mel_basis(hparams))
    else:
         _inv_mel_basis = hparams.inv_mel_basis
    return np.maximum(1e-10, np.dot(_inv_mel_basis, mel_spectrogram))
'''

**Comment by KuangDD** [comment]
您好，谢谢您的issue，新版本修正这个bug。
