### ISSUE TITLE
关于生成的音频文件是否可以更改每个样本的位数为32

### ISSUE THREAD

**Issue by xyjsjruiliu** [KuangDD/aukit#6]
主要是因为后期再处理的时候使用32的，16的处理有问题

**Comment by xyjsjruiliu** [comment]
最后试了下可以修改audio_io.py文件中的_int16_max = 2 ** 15 - 1和wavfile.write(path, sr, out.astype(np.int16))。分别修改为_int16_max = 2 ** 31 - 1和wavfile.write(path, sr, out.astype(np.int32))就可以，不知道是不

**Comment by KuangDD** [comment]
可以这样操作。
